---
abstract: 'a interface to Prowl Public API'
author:
  - 'Masayoshi Sekimura <sekimura@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
  Test::More: '0'
configure_requires:
  CPAN::Meta: '0'
  ExtUtils::MakeMaker: '6.59'
dynamic_config: '0'
generated_by: 'Module::Install version 1.16, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Prowl
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  AnyEvent::HTTP: '0'
  Carp: '0'
  Filter::Util::Call: '0'
  LWP::Protocol::https: '0'
  LWP::UserAgent: '6.02'
  URI::Escape: '0'
  XML::Simple: '0'
  perl: v5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/sekimura/WebService-Prowl.git
version: '0.07'
